### ISSUE TITLE
Status Bar Background

### ISSUE THREAD

**Issue by archieherbias** [crazycodeboy/react-native-splash-screen#95]
Is it possible to change the status bar color of the splashscreen?

**Comment by hoboman313** [comment]
@crazycodeboy do you know if this is possible/easy to do with this library? I saw in the code that you can pass true to show() for fullscreen, but it's not quite as good as coloring the status bar.

**Comment by hoboman313** [comment]
The easiest way that I found is to monkey patch your status bar color like `<item name="colorPrimaryDark">#400101</item>` into **res/values/styles.xml**'s **SplashScreen_SplashTheme** and (if you need it) **SplashScreen_Fullscreen** styles from this library.

**Comment by Noor0** [comment]
status bar is black and the icons are also black this issue still persists

**Comment by AE0011** [comment]
this version works right:
`"react-native-splash-screen": "^3.0.6"`

also add 
`<color name="primary_dark">#2b8ce5</color>` this in colors.xml

**Comment by chico** [comment]
It works as long as you also change your `show` method to include your custom style.

From the README:

If you want to customize the color of the status bar when the splash screen is displayed:

Create `android/app/src/main/res/values/colors.xml` and add
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="status_bar_color"><!-- Colour of your status bar here --></color>
</resources>
```

Create a style definition for this in `android/app/src/main/res/values/styles.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="SplashScreenTheme" parent="SplashScreen_SplashTheme">
        <item name="colorPrimaryDark">@color/status_bar_color</item>
    </style>
</resources>
```

Change your `show` method to include your custom style:
```java
SplashScreen.show(this, R.style.SplashScreenTheme);
```

**Comment by rizkiandrianto** [comment]
> It works as long as you also change your `show` method to include your custom style.
> 
> From the README:
> 
> If you want to customize the color of the status bar when the splash screen is displayed:
> 
> Create `android/app/src/main/res/values/colors.xml` and add
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <resources>
>     <color name="status_bar_color"></color>
> </resources>
> ```
> 
> Create a style definition for this in `android/app/src/main/res/values/styles.xml`:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <resources>
>     <style name="SplashScreenTheme" parent="SplashScreen_SplashTheme">
>         <item name="colorPrimaryDark">@color/status_bar_color</item>
>     </style>
> </resources>
> ```
> 
> Change your `show` method to include your custom style:
> 
> ```java
> SplashScreen.show(this, R.style.SplashScreenTheme);
> ```

Hey @chico I got this error if I change my show method like this

![image](https://user-images.githubusercontent.com/2457820/50823159-ea988700-1365-11e9-9775-1aabad1c7e54.png)

**Comment by Noor0** [comment]
@rizkiandrianto `R.style.SplashTheme` the symbol after the style should match the name of the theme inside `styles.xml`

in my case the name of the theme was `SplashTheme`
```
<resources>
    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
    </style>

    <style name="SplashTheme" parent="Theme.AppCompat.Light.NoActionBar">
	<item name="android:windowBackground">@drawable/background_splash</item>
	<item name="android:statusBarColor">@color/splash_background</item>
    </style>
</resources>
```

so I'm passing `R.style.SplashTheme` to my `SplashScreen.show()`
```
SplashScreen.show(this, R.style.SplashTheme);
```

**Comment by ramon90** [comment]
For some reason addid `SplashScreen.show(this, R.style.SplashTheme);
` causes white screen flash between splash screen and app mounting, any one facing the same issue or know a fix?

**Comment by kg-currenxie** [comment]
@ramon90 i fixed the white screen with
```
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:statusBarColor">@color/bg</item>
        <item name="android:windowIsTranslucent">true</item> <--------- add this
    </style>
```

**Comment by dogukny** [comment]
You can give different status bar colors for different splash screen themes (like dark theme)

Just add `R.style.Theme`
```
   switch (getResources().getConfiguration().uiMode & Configuration.UI_MODE_NIGHT_MASK) {
            case Configuration.UI_MODE_NIGHT_YES:
                setTheme(R.style.DarkTheme);

                break;
            case Configuration.UI_MODE_NIGHT_NO:
                setTheme(R.style.LightTheme);
                break;
            default:
                setTheme(R.style.LightTheme);
        }

        SplashScreen.show(this, R.style.Theme);
```

**Comment by parth-koshta** [comment]
> @RAMON90 i fixed the white screen with
> 
> ```
>     <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
>         <item name="android:statusBarColor">@color/bg</item>
>         <item name="android:windowIsTranslucent">true</item> <--------- add this
>     </style>
> ```
This didn't resolve white screen flash between splash screen and app mounting

**Comment by parth-koshta** [comment]
> For some reason addid `SplashScreen.show(this, R.style.SplashTheme); ` causes white screen flash between splash screen and app mounting, any one facing the same issue or know a fix?

were you able to solve this?

**Comment by Revolt9k** [comment]
If none of this methods allow you to trick conversion error, add true as a third arg of show method like this
```    SplashScreen.show(this, R.style.SplashTheme, true); ``` 
Change it to false to disable fullscreen

**Comment by JJalit** [comment]
I fixed this problem
I just add `true`
`SplashScreen.show(this, true);`

**Comment by mathieumousnier** [comment]
Something might have changed in last versions of android.

This gives me an error telling that the second argument should be a boolean:
`SplashScreen.show(this, R.style.SplashTheme);`

And this makes the statusBar and the navigationBar with the background color:
`SplashScreen.show(this, true);`

**Comment by Malik-Usman17** [comment]
> 

Thanks for the solution, just a little change what I did is to add a third argument **true (boolean value)** in  SplashScreen.show method
